# 土地配置文件
# 定义土地解锁、品质升级等

land:
  # 土地解锁配置
  expansion:
    land_expansion_1:
      name: "农场扩建I"
      cost: 500 # 解锁费用
      requiredLevel: 4 # 所需等级
      additionalSlots: 2 # 增加土地槽位数
      description: "扩建农场，增加2个种植槽位"

    land_expansion_2:
      name: "农场扩建II"
      cost: 1200 # 解锁费用
      requiredLevel: 5 # 所需等级
      additionalSlots: 3 # 增加土地槽位数
      description: "进一步扩建农场，增加3个种植槽位"

    land_expansion_3:
      name: "农场扩建III"
      cost: 2500 # 解锁费用
      requiredLevel: 8 # 所需等级
      additionalSlots: 5 # 增加土地槽位数
      description: "大规模扩建农场，增加5个种植槽位"

  # 土地品质配置
  quality:
    poor:
      name: "贫瘠"
      multiplier: 0.8 # 产量倍数
      growTimeMultiplier: 1.2 # 生长时间倍数
      upgradeChance: 0.05 # 自然升级概率

    normal:
      name: "普通"
      multiplier: 1.0 # 产量倍数
      growTimeMultiplier: 1.0 # 生长时间倍数
      upgradeChance: 0.03 # 自然升级概率

    fertile:
      name: "肥沃"
      multiplier: 1.3 # 产量倍数
      growTimeMultiplier: 0.9 # 生长时间倍数
      upgradeChance: 0.01 # 自然升级概率

    rich:
      name: "富饶"
      multiplier: 1.6 # 产量倍数
      growTimeMultiplier: 0.8 # 生长时间倍数
      upgradeChance: 0 # 最高品质，无法升级

  # 初始配置
  defaults:
    startingSlots: 4 # 初始土地槽位数
    defaultQuality: "normal" # 默认土地品质
